### ISSUE TITLE
Re-design the theme

### ISSUE THREAD

**Issue by Defman21** [Xenite/Xenite#72]
**Apps**
- [x] Fix pantheon-mail (selected items are white)
- [ ] Fix Video
- [ ] Make pantheon-calculator white and light

**General**
- [ ] Replace blue with orange everywhere
- [ ] Update GTK2 theme
- [ ] Fix dark theme

**Notifications**
- [ ] Re-design notifications

**Comment by Defman21** [comment]
@Xenite/co-authors do not push anything to the development branch. Just a notice.

**Comment by vinctux** [comment]
@Defman21 OK, roger. I just updated the `README` a bit, in `master`. Now it's a bit more secure for the user - not that they pipe a random script from the Web into `sudo`. That was a seriously dangerous way...

**Comment by Defman21** [comment]
Yeah I saw that. Nice job on that! :)
