### ISSUE TITLE
When uninstalling Xenite, change the theme to default

### ISSUE THREAD

**Issue by Defman21** [Xenite/Xenite#73]
We don't want to break the interface.

**Comment by vinctux** [comment]
@Defman21 Will be done.

**Comment by vinctux** [comment]
This will be indeed difficult to implement... It depends greatly which DM the user is using. Under GNOME, it should be easily done (it is already in the scripts), whereas other DMs (like XFCE, Unity) require deeper investigation, although I doubt that I'll be able to produce something of use in the near future. So, the milestone seems a bit too much for the moment.

**TL;DR:** On GNOME it should work as of now, other DMs require deep investigation how it can be done, if it's even possible.

**Comment by Defman21** [comment]
There should be a way of calling custom functions in uninstall process (an example would be the list of dependencies in the installation script). Since I don't care about any other DE's, I'd want to reset pantheon-related settings.

**Comment by vinctux** [comment]
Oh, that's another story :smile: I'll add the option to purge the dependencies in `uninstall.sh` iff they had been installed on behalf of `install.sh`, probably in `themeon` `v1.0.1`. Regarding all other settings, let me know which are relevant to Xenite. (It'll take time though, as I must get Loki Beta 2.)

**Comment by Defman21** [comment]
You didn't get me. The dependencies was an example. I'd want to see some sort of list where I can define what commands should be run after the uninstall process.

**Comment by vinctux** [comment]
Yeah, I think that was what I tried to say with 

> Regarding all other settings

 Anyway, I just figured out, that it could be of gain to remove the setup scripts from the direct Xenite source, and just modify the themeon script (in say, version `1.1`) to be used also completely remotely. It would spare me the overhead with constantly updating a doubled codebase.

So, perhaps from
```shell
./install.sh
```
into
```shell
./install.sh https://raw.githubusercontent.com/Xenite/Xenite/master/Xenite.tconf
```
which would remotely call the internal config (author, theme, version, etc.) into the master themeon script. I'll try to do it ASAP.


Sample `Xenite.tconf`:
```
[themeon Configuration Script v1.1]
[GENERAL]
MODE=1
THEME="Xenite"
AUTHOR="Xenite"
VERSION="v1.0"
DEPS=(gtk2-engines-pixbuf)
GSETTINGS=0

[INSTALL]
PREEXEC=("echo Hello World!")
POSTEXEC=("echo Bye World!")

[UPDATE]
INSTDIR="./"
EXECF="install.sh"
PREEXEC=("echo Hello World!")
POSTEXEC=("echo Bye World!")

[UNINSTALL]
PURGE=false
PREEXEC=("echo Hello World!")
POSTEXEC=("echo Bye World!")
```

**Comment by vinctux** [comment]
@Defman21 :tada: New [themeon](https://github.com/vinctux/themeon) is here! :tada: I updated Xenite accordingly.

**Comment by Defman21** [comment]
Nice job. Once I'll finish with #72, I'll update Xenite.tconf.

**Comment by vinctux** [comment]
@Defman21 Now even simpler :tada:

1. Run `themeon build Xenite Xenite.tconf` in the Xenite root folder.
2. Fill in like this:

 ```shell
 THEME="Xenite"
 AUTHOR="Xenite"
 RELEASE="v1.0"
 ```

3. Add all your pre-/post-{install, update, uninstall} things into the according place, **between the last comment and `EOL`**. Like:

 ```shell
 cat > $TEXECDIR/REMOVE_POSTEXEC-$THEME.texe << EOL
 #============= themeon $THEME Post-Uninstall ===============#
 # Write your post-uininstall commands here.
 # Ensure that all commands are written
 # in a secure manner (no piping of random scripts
 # from the web) and use as little of sudo as possible.
 
sudo apt-get remove unity --purge

 EOL
 ```

4. Commit changes. And you are done!
