### ISSUE TITLE
Don't install any icons in postinstall

### ISSUE THREAD

**Issue by Defman21** [Xenite/Xenite#74]
I'd prefer to have the default icons for this theme.

**Comment by vinctux** [comment]
@Defman21 Do we (as the publisher of Xenite) still recommend Numix? In the end, it's any way the user's choice but back then we considered them as a recommendation, so I'd added them into `postinstall.sh`. If we aren't OK with it anymore, I'll remove that piece of code ASAP. Also, if any other recommendations are up, I'll add them, I just need to know :)

**Comment by Defman21** [comment]
I don't really have any things to recommend in my mind nor I want to have users to install Numix. I think this could cause some problems with wingpanel because they are stylizing the indicators using CSS (I mean the colors).

**Comment by vinctux** [comment]
@Defman21 OK, I didn't know that Numix could cause Xenite trouble. I'll remove it from `post-install.sh`.

**Comment by Defman21** [comment]
I don't know if it could cause some troubles, I just think it could. I don't want to test it :P

**Comment by vinctux** [comment]
Resolved.
