### ISSUE TITLE
Fix update script

### ISSUE THREAD

**Issue by Defman21** [Xenite/Xenite#75]
It should detect the way preferred in installation (per-user or system-wide) and run the installation script depends on it. Atm it just run `install.sh` with sudo which could break some things.

**Comment by vinctux** [comment]
@Defman21 Yeah, `update.sh` is currently more or less just a reroute to `install.sh`. I'll fix that in the near future. Oh, and please report this kind of bugs/recommendation/improvements/whatsoever to [`themeon`](https://github.com/vinctux/themeon/issues)'s bugtracker.

**Comment by Defman21** [comment]
@vinctux okay.

**Comment by vinctux** [comment]
Resolved.
