### ISSUE TITLE
Plank issue in installation process?

### ISSUE THREAD

**Issue by Defman21** [Xenite/Xenite#76]
@vinctux https://github.com/Xenite/Xenite/blob/master/setup/install.sh#L106 is there an issue with plank not working when it's placed in a theme directory? It works fine for me.

**Comment by vinctux** [comment]
@Defman21 Nope but some time ago, issues were reported otherwhere, so I included a general fix for that. A bugfix before the bug occurs ;)

**Comment by crutchcorn** [comment]
J

**Comment by Defman21** [comment]
@crutchcorn seems like you didn't complete your reply..

**Comment by vinctux** [comment]
@crutchcorn Or did you want to send a smiley? I saw really _A LOT_ of people recently sending me emails with a `J` at the end of every line. Later they told me they wanted a normal `:)` there. Irony.

**Comment by Defman21** [comment]
@vinctux I can't invite you in Gitter. Did you set any restrictions about inviting you in groups?

**Comment by vinctux** [comment]
@Defman21 Nope, not that I know of that. Maybe an evil FBI guy, who knows? :P

**Comment by Defman21** [comment]
@vinctux nvm, there were a bug.

**Comment by vinctux** [comment]
@Defman21 I'm in now.
